In [11]:
# Import Pandas and NumPy

import numpy as np
import pandas as pd

#pip install db-sqlite3
#SQLite in general is a server-less database that you can use within almost all programming languages including Python.
import sqlite3

We import the sqlite3 module and then create a connection object which will connect us to the database and will let us execute the SQL statements.

sqlite3.connect(Database)

__cursor()__ - we can use the cursor object to call the execute() method to execute any SQL queries.

__STEPS:__
To query data in an SQLite database from Python, you use these steps:

- First, establish a connection to the SQLite database by creating a Connection object.
- Next, create a Cursor object using the cursor method of the Connection object.
- Then, execute a SELECT statement.
- After that, call the fetchall() method of the cursor object to fetch the data.
- Finally, loop the cursor and process each row individually.

In [12]:
db = 'movies.sqlite'


conn = sqlite3.connect(db)
cur = conn.cursor()

## QUESTIONS
### Question 1: Can you get all data about movies?

In [13]:
cur.execute('SELECT * FROM movies')
#use the cursor object to call the execute() method to execute any SQL queries.
movies = cur.fetchall()

#movies -> if u print movies , all the data shown in list manner, can't understanadble

#Note - fetchall() --> fetch all rows for the current query, if no rows avaliable then,it returns an empty list.

movies = pd.DataFrame(movies, columns = ['id', 'original_title', 'budget', 'popularity', 'release_date', 'revenue', 'title', 'vote_average', 'vote_count', 'overview', 'tagline', 'uid', 'director_id'])
#Creating a dataframe, A dataframe contains rows and columns , It is a Two-dimensional, size-mutable, potentially heterogeneous tabular data.

print('Shape of Movies data :',movies.shape)
print('\n\n\n')
movies.head(10)
#Displays first 3 rows in the table

Shape of Movies data : (4773, 13)

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,206647,4764
3,43600,The Dark Knight Rises,250000000,112,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,The Legend Ends,49026,4765
4,43601,John Carter,260000000,43,2012-03-07,284139100,John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",49529,4766
5,43602,Spider-Man 3,258000000,115,2007-05-01,890871626,Spider-Man 3,5.9,3576,The seemingly invincible Spider-Man goes up ag...,The battle within.,559,4767
6,43603,Tangled,260000000,48,2010-11-24,591794936,Tangled,7.4,3330,When the kingdom's most wanted-and most charmi...,They're taking adventure to new lengths.,38757,4768
7,43604,Avengers: Age of Ultron,280000000,134,2015-04-22,1405403694,Avengers: Age of Ultron,7.3,6767,When Tony Stark tries to jumpstart a dormant p...,A New Age Has Come.,99861,4769
8,43605,Harry Potter and the Half-Blood Prince,250000000,98,2009-07-07,933959197,Harry Potter and the Half-Blood Prince,7.4,5293,"As Harry begins his sixth year at Hogwarts, he...",Dark Secrets Revealed,767,4770
9,43606,Batman v Superman: Dawn of Justice,250000000,155,2016-03-23,873260194,Batman v Superman: Dawn of Justice,5.7,7004,Fearing the actions of a god-like Super Hero l...,Justice or revenge,209112,4771

In [14]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4773 entries, 0 to 4772
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              4773 non-null   int64
 1   original_title  4773 non-null   object
 2   budget          4773 non-null   int64
 3   popularity      4773 non-null   int64
 4   release_date    4773 non-null   object
 5   revenue         4773 non-null   int64
 6   title           4773 non-null   object
 7   vote_average    4773 non-null   float64
 8   vote_count      4773 non-null   int64
 9   overview        4770 non-null   object
 10  tagline         3951 non-null   object
 11  uid             4773 non-null   int64
 12  director_id     4773 non-null   int64
dtypes: float64(1), int64(7), object(5)
memory usage: 484.9+ KB

## Question 2: How do you get all data about directors?

In [15]:
cur.execute('SELECT * FROM directors')
#use the cursor object to call the execute() method to execute any SQL queries.

directors = cur.fetchall()
#Note - fetchall() --> fetch all rows for the current query, if no rows avaliable then,it returns an empty list.


directors = pd.DataFrame(directors, columns = ['name', 'id', 'gender', 'uid', 'department'])
#Creating a dataframe, A dataframe contains rows and columns , It is a Two-dimensional, size-mutable, potentially heterogeneous tabular data.

print('Shape of Directors data :',directors.shape)
print('\n\n\n')


directors.head(11)

Shape of Directors data : (2349, 5)

                 name    id  gender    uid department
0       James Cameron  4762       2   2710  Directing
1      Gore Verbinski  4763       2   1704  Directing
2          Sam Mendes  4764       2     39  Directing
3   Christopher Nolan  4765       2    525  Directing
4      Andrew Stanton  4766       2      7  Directing
5           Sam Raimi  4767       2   7623  Directing
6        Byron Howard  4768       2  76595  Directing
7         Joss Whedon  4769       2  12891  Directing
8         David Yates  4770       2  11343  Directing
9         Zack Snyder  4771       2  15217  Directing
10       Bryan Singer  4772       2   9032  Directing

In [16]:
directors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2349 entries, 0 to 2348
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        2349 non-null   object
 1   id          2349 non-null   int64
 2   gender      2349 non-null   int64
 3   uid         2349 non-null   int64
 4   department  2349 non-null   object
dtypes: int64(3), object(2)
memory usage: 91.9+ KB

## Question 3: Check how many movies are present in iMDB.

In [17]:
## Question 3: Check how many movies are present in IMDB.

cur.execute("SELECT COUNT(*) FROM movies")
count_movies = cur.fetchone()

print("Total number of movies :", count_movies[0])

Total number of movies : 4773

In [18]:
## Question 4: Find these 3 directors: James Cameron ; Luc Besson ; John Woo

cur.execute("""
SELECT * FROM directors
WHERE name IN ('James Cameron', 'Luc Besson', 'John Woo')
""")

directors_data = cur.fetchall()

directors_data = pd.DataFrame(
    directors_data,
    columns=['name', 'id', 'gender', 'uid', 'department']
)

directors_data

            name    id  gender    uid department
0  James Cameron  4762       2   2710  Directing
1       John Woo  4893       2  11401  Directing
2     Luc Besson  4949       2     59  Directing

In [19]:
## Question 5: Find all directors with name starting with Steven.

cur.execute("""
SELECT * FROM directors
WHERE name LIKE 'Steven%'
""")

steven_directors = cur.fetchall()

steven_directors = pd.DataFrame(
    steven_directors,
    columns=['name', 'id', 'gender', 'uid', 'department']
)

steven_directors

                 name    id  gender    uid department
0    Steven Spielberg  4799       2    488  Directing
1   Steven Soderbergh  4909       2   1884  Directing
2        Steven Brill  5013       2  32593  Directing
3     Steven Zaillian  5117       2   2260  Directing
4        Steven Quale  5216       2  93214  Directing
5       Steven Seagal  5221       2  23880  Directing
6  Steven E. de Souza  5390       2   1726  Directing
7    Steven Shainberg  5803       2  67795  Directing
8    Steven R. Monroe  6713       2  88039  Directing

In [20]:
## Question 6: Count female directors.

cur.execute("""
SELECT COUNT(*) FROM directors
WHERE gender = 1
""")

female_directors = cur.fetchone()

print("Total Female Directors :", female_directors[0])

Total Female Directors : 150

In [21]:
## Question 7: Find the name of the 10th first women directors.

cur.execute("""
SELECT name FROM directors
WHERE gender = 1
LIMIT 1 OFFSET 9
""")

tenth_woman_director = cur.fetchone()

print("10th Woman Director :", tenth_woman_director[0])

10th Woman Director : Angelina Jolie

In [22]:
## Question 8: What are the 3 most popular movies?

cur.execute("""
SELECT title, popularity
FROM movies
ORDER BY popularity DESC
LIMIT 3
""")

popular_movies = cur.fetchall()

popular_movies = pd.DataFrame(
    popular_movies,
    columns=['Movie Name', 'Popularity']
)

popular_movies

     Movie Name  Popularity
0       Minions         875
1  Interstellar         724
2      Deadpool         514

In [23]:
## Question 9: What are the 3 most bankable movies?

cur.execute("""
SELECT title, revenue, budget, (revenue - budget) AS profit
FROM movies
ORDER BY profit DESC
LIMIT 3
""")

bankable_movies = cur.fetchall()

bankable_movies = pd.DataFrame(
    bankable_movies,
    columns=['Movie Name', 'Revenue', 'Budget', 'Profit']
)

bankable_movies

       Movie Name     Revenue     Budget      Profit
0          Avatar  2787965087  237000000  2550965087
1         Titanic  1845034188  200000000  1645034188
2  Jurassic World  1513528810  150000000  1363528810

In [24]:
## Question 10: What is the most awarded average vote since January 1st, 2000?

cur.execute("""
SELECT title, vote_average
FROM movies
WHERE release_date >= '2000-01-01'
ORDER BY vote_average DESC
LIMIT 1
""")

top_voted_movie = cur.fetchall()

top_voted_movie = pd.DataFrame(
    top_voted_movie,
    columns=['Movie Name', 'Vote Average']
)

top_voted_movie

  Movie Name  Vote Average
0  Sardaarji           9.5

In [25]:
## Question 11: Which movie(s) were directed by Brenda Chapman?

cur.execute("""
SELECT movies.title
FROM movies
JOIN directors
ON movies.director_id = directors.id
WHERE directors.name = 'Brenda Chapman'
""")

brenda_movies = cur.fetchall()

brenda_movies = pd.DataFrame(
    brenda_movies,
    columns=['Movie Name']
)

brenda_movies

  Movie Name
0      Brave

In [26]:
## Question 12: Whose director made the most movies?

cur.execute("""
SELECT directors.name, COUNT(movies.id) AS total_movies
FROM movies
JOIN directors
ON movies.director_id = directors.id
GROUP BY directors.name
ORDER BY total_movies DESC
LIMIT 1
""")

most_movies_director = cur.fetchall()

most_movies_director = pd.DataFrame(
    most_movies_director,
    columns=['Director Name', 'Total Movies']
)

most_movies_director

      Director Name  Total Movies
0  Steven Spielberg            27